// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUud3_dOYFn2c2YWLGhy3VEvhYyPmsivM',
    appId: '1:617711073689:web:2b6d2bdbb4b6018e927b08',
    messagingSenderId: '617711073689',
    projectId: 'aggoapp',
    authDomain: 'aggoapp.firebaseapp.com',
    storageBucket: 'aggoapp.firebasestorage.app',
    measurementId: 'G-DLHR43XJT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASwZz13ZeqL9Z7K4I8Zmi8onbXe0HN42E',
    appId: '1:617711073689:android:7035f320b943892f927b08',
    messagingSenderId: '617711073689',
    projectId: 'aggoapp',
    storageBucket: 'aggoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo8EMdsjYPV7tlboZs8-Z16OyUGzjzGZg',
    appId: '1:617711073689:ios:b5f47e685bae44af927b08',
    messagingSenderId: '617711073689',
    projectId: 'aggoapp',
    storageBucket: 'aggoapp.firebasestorage.app',
    iosBundleId: 'com.isotech.aggo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo8EMdsjYPV7tlboZs8-Z16OyUGzjzGZg',
    appId: '1:617711073689:ios:b5f47e685bae44af927b08',
    messagingSenderId: '617711073689',
    projectId: 'aggoapp',
    storageBucket: 'aggoapp.firebasestorage.app',
    iosBundleId: 'com.isotech.aggo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUud3_dOYFn2c2YWLGhy3VEvhYyPmsivM',
    appId: '1:617711073689:web:1acba9a1b258dc5e927b08',
    messagingSenderId: '617711073689',
    projectId: 'aggoapp',
    authDomain: 'aggoapp.firebaseapp.com',
    storageBucket: 'aggoapp.firebasestorage.app',
    measurementId: 'G-FP532WTW4H',
  );

}
